---
title: "NM2207 Project Dataset"
---

# Project Introduction: The Social Impact of Influencers on Market Value

## What am I doing?

Like many others, I'm intrigued by the trends in the stock market and the cryptocurrency space. Specifically, I'm focusing on a memorable event from 2021 - the Dogecoin hype. This cryptocurrency, initially started as a joke, saw its value skyrocket and plummet within a short time span. I'm particularly interested in the role of Elon Musk, whose tweets about Dogecoin in 2021 seemingly influenced its market value significantly.

## Why am I doing this?

The main point of my analysis is to explore the power of social media influencers, like Elon Musk, over financial markets. I aim to understand how an individual's statements, whether factually grounded or not, can have a tangible impact on stock or cryptocurrency values.

## What will I be using?

To conduct this analysis, I will be utilizing two primary data sources:

1.  **2021 Historical Prices for Dogecoin:** This dataset, obtained from Kaggle, will provide the necessary information about Dogecoin's price fluctuations throughout 2021.

2.  **2021 Elon Musk's Tweets Related to Dogecoin:** I'll be examining Elon Musk's tweets from 2021 that mention Dogecoin, available on Twitter and compiled in a dataset on Kaggle.

## Goals of the Analysis

With this data, I hope to create visualizations that illustrate the correlation between Dogecoin's market performance and Elon Musk's tweets. This analysis will not only shed light on the specific Dogecoin phenomenon but also contribute to the broader understanding of the influence of social media on financial markets.

------------------------------------------------------------------------

## Dogecoin Price Visualization Interactive Chart

To get a sense of our dataset's characteristics, it's helpful to start by examining the data directly. Our dataset includes detailed Dogecoin price movements throughout the year 2021.

For a deeper dive and an interactive exploration of Dogecoin's price trends, please visit our Shiny application:

<a href="http://dwayneyoongty00.shinyapps.io/myapp" target="_blank" style="color: #1e90ff; font-weight: bold; text-decoration: none;">Interactive Dogecoin Price Visualization</a>


