---
title: "Dwayne Yoong's NM2207 Website"
---

# Hi! I'm Dwayne Yoong

## About Me

I'm currently a **2nd year Psychology major**. My journey in the realm of psychology has led me to the fascinating world of **R programming**.

## My Interests

One of the subjects I'm taking this year is `NM2207`, which focuses on understanding the nuances of R programming. I have a deep-seated interest in **statistics**, and I believe that mastering R programming is pivotal in the psychological research field. Currently, I have a multitude of Statistics module such as PL2132, GEA1000, GEI1001, IT1244, and I'm hopping NM2207 would guide me towards a path into R statistics in Psychology

## My Goals

I am eager to learn how to read and evaluate datasets effectively. My goal is to extract **meaningful trends** and insights, which are crucial for psychological research. I believe that with these skills, I can contribute significantly to the field and expand my knowledge in areas that intersect psychology and data analysis.

---

# Project Introducxtion: The Social Impact of Influencers on Market Value

## What am I doing?

Like many others, I'm intrigued by the trends in the stock market and the cryptocurrency space. Specifically, I'm focusing on a memorable event from 2021 - the Dogecoin hype. This cryptocurrency, initially started as a joke, saw its value skyrocket and plummet within a short time span. I'm particularly interested in the role of Elon Musk, whose tweets about Dogecoin in 2021 seemingly influenced its market value significantly.

## Why am I doing this?

The main point of my analysis is to explore the power of social media influencers, like Elon Musk, over financial markets. I aim to understand how an individual's statements, whether factually grounded or not, can have a tangible impact on stock or cryptocurrency values.

## What will I be using?

To conduct this analysis, I will be utilizing two primary data sources:

1. **2021 Historical Prices for Dogecoin:** This dataset, obtained from Kaggle, will provide the necessary information about Dogecoin's price fluctuations throughout 2021.

2. **2021 Elon Musk's Tweets Related to Dogecoin:** I'll be examining Elon Musk's tweets from 2021 that mention Dogecoin, available on Twitter and compiled in a dataset on Kaggle.

## Goals of the Analysis

With this data, I hope to create visualizations that illustrate the correlation between Dogecoin's market performance and Elon Musk's tweets. This analysis will not only shed light on the specific Dogecoin phenomenon but also contribute to the broader understanding of the influence of social media on financial markets.
